#include <pybind11/pybind11.h>
namespace py = pybind11;

void init_encoders(py::module &handle) {

	py::enum_<enums::ENCODER_TYPE>(handle, "ENCODER_TYPE", py::arithmetic())
    .value("EL_VELOCITY_DURATION_POLYPHONY_YELLOW_ENCODER", enums::ENCODER_TYPE::EL_VELOCITY_DURATION_POLYPHONY_YELLOW_ENCODER)
    .value("EXPRESSIVE_ENCODER", enums::ENCODER_TYPE::EXPRESSIVE_ENCODER)
    .value("STEINBERG_WPCS_ENCODER", enums::ENCODER_TYPE::STEINBERG_WPCS_ENCODER)
    .value("STEINBERG_W_P_C_S_ENCODER", enums::ENCODER_TYPE::STEINBERG_WPCS_ENCODER)
    .value("GHOST_ENCODER", enums::ENCODER_TYPE::GHOST_ENCODER)
    .value("SPECTER_ENCODER", enums::ENCODER_TYPE::SPECTER_ENCODER)
    .value("ORACLE_ENCODER", enums::ENCODER_TYPE::ORACLE_ENCODER)
		.value("NO_ENCODER", enums::ENCODER_TYPE::NO_ENCODER)
		.export_values();

  py::class_<encoder::ElVelocityDurationPolyphonyYellowEncoder>(handle, "ElVelocityDurationPolyphonyYellowEncoder")
    .def(py::init<>())
    .def("encode", &encoder::ElVelocityDurationPolyphonyYellowEncoder::encode)
    .def("decode", &encoder::ElVelocityDurationPolyphonyYellowEncoder::decode)
    .def("midi_to_json", &encoder::ElVelocityDurationPolyphonyYellowEncoder::midi_to_json)
    .def("midi_to_tokens", &encoder::ElVelocityDurationPolyphonyYellowEncoder::midi_to_tokens)
    .def("json_to_midi", &encoder::ElVelocityDurationPolyphonyYellowEncoder::json_to_midi)
    .def("json_track_to_midi", &encoder::ElVelocityDurationPolyphonyYellowEncoder::json_track_to_midi)
    .def("json_to_tokens", &encoder::ElVelocityDurationPolyphonyYellowEncoder::json_to_tokens)
    .def("tokens_to_json", &encoder::ElVelocityDurationPolyphonyYellowEncoder::tokens_to_json)
    .def("tokens_to_midi", &encoder::ElVelocityDurationPolyphonyYellowEncoder::tokens_to_midi)
    .def("pretty", &encoder::ElVelocityDurationPolyphonyYellowEncoder::pretty)
    .def("vocab_size", &encoder::ElVelocityDurationPolyphonyYellowEncoder::vocab_size)
    .def("get_attribute_control_types", &encoder::ElVelocityDurationPolyphonyYellowEncoder::get_attribute_control_types)
    .def_readonly("config", &encoder::ElVelocityDurationPolyphonyYellowEncoder::config)
    .def_readonly("rep", &encoder::ElVelocityDurationPolyphonyYellowEncoder::rep);

  py::class_<encoder::SpecterEncoder>(handle, "SpecterEncoder")
    .def(py::init<>())  
    .def("encode", &encoder::SpecterEncoder::encode)
    .def("decode", &encoder::SpecterEncoder::decode)
    .def("midi_to_json", &encoder::SpecterEncoder::midi_to_json)
    .def("midi_to_tokens", &encoder::SpecterEncoder::midi_to_tokens)
    .def("json_to_midi", &encoder::SpecterEncoder::json_to_midi)
    .def("json_track_to_midi", &encoder::SpecterEncoder::json_track_to_midi)
    .def("json_to_tokens", &encoder::SpecterEncoder::json_to_tokens)
    .def("tokens_to_json", &encoder::SpecterEncoder::tokens_to_json)
    .def("tokens_to_midi", &encoder::SpecterEncoder::tokens_to_midi)
    .def("pretty", &encoder::SpecterEncoder::pretty)
    .def("vocab_size", &encoder::SpecterEncoder::vocab_size)
    .def("get_attribute_control_types", &encoder::SpecterEncoder::get_attribute_control_types)
    .def("set_use_tension", &encoder::SpecterEncoder::set_use_tension)
    .def_readonly("config", &encoder::SpecterEncoder::config)
    .def_readonly("rep", &encoder::SpecterEncoder::rep);

  py::class_<encoder::OracleEncoder>(handle, "OracleEncoder")
    .def(py::init<>())  
    .def("encode", &encoder::OracleEncoder::encode)
    .def("decode", &encoder::OracleEncoder::decode)
    .def("midi_to_json", &encoder::OracleEncoder::midi_to_json)
    .def("midi_to_tokens", &encoder::OracleEncoder::midi_to_tokens)
    .def("json_to_midi", &encoder::OracleEncoder::json_to_midi)
    .def("json_track_to_midi", &encoder::OracleEncoder::json_track_to_midi)
    .def("json_to_tokens", &encoder::OracleEncoder::json_to_tokens)
    .def("tokens_to_json", &encoder::OracleEncoder::tokens_to_json)
    .def("tokens_to_midi", &encoder::OracleEncoder::tokens_to_midi)
    .def("pretty", &encoder::OracleEncoder::pretty)
    .def("vocab_size", &encoder::OracleEncoder::vocab_size)
    .def("get_attribute_control_types", &encoder::OracleEncoder::get_attribute_control_types)
    .def("set_use_tension", &encoder::OracleEncoder::set_use_tension)
    .def("update_internal_features", &encoder::OracleEncoder::update_internal_features)
    .def_readonly("config", &encoder::OracleEncoder::config)
    .def_readonly("rep", &encoder::OracleEncoder::rep);

  py::class_<encoder::ExpressiveEncoder>(handle, "ExpressiveEncoder")
    .def(py::init<>())
    .def("encode", &encoder::ExpressiveEncoder::encode)
    .def("decode", &encoder::ExpressiveEncoder::decode)
    .def("midi_to_json", &encoder::ExpressiveEncoder::midi_to_json)
    .def("midi_to_tokens", &encoder::ExpressiveEncoder::midi_to_tokens)
    .def("json_to_midi", &encoder::ExpressiveEncoder::json_to_midi)
    .def("json_track_to_midi", &encoder::ExpressiveEncoder::json_track_to_midi)
    .def("json_to_tokens", &encoder::ExpressiveEncoder::json_to_tokens)
    .def("tokens_to_json", &encoder::ExpressiveEncoder::tokens_to_json)
    .def("resample_delta_json", &encoder::ExpressiveEncoder::resample_delta_json)
    .def("tokens_to_midi", &encoder::ExpressiveEncoder::tokens_to_midi)
    .def("pretty", &encoder::ExpressiveEncoder::pretty)
    .def("vocab_size", &encoder::ExpressiveEncoder::vocab_size)
    .def("get_attribute_control_types", &encoder::ExpressiveEncoder::get_attribute_control_types)
    .def("set_scheme", &encoder::ExpressiveEncoder::set_scheme)
    .def_readonly("config", &encoder::ExpressiveEncoder::config)
    .def_readonly("rep", &encoder::ExpressiveEncoder::rep);

  py::class_<encoder::SteinbergWPCSEncoder>(handle, "SteinbergWPCSEncoder")
    .def(py::init<>())
    .def("encode", &encoder::SteinbergWPCSEncoder::encode)
    .def("decode", &encoder::SteinbergWPCSEncoder::decode)
    .def("midi_to_json", &encoder::SteinbergWPCSEncoder::midi_to_json)
    .def("midi_to_tokens", &encoder::SteinbergWPCSEncoder::midi_to_tokens)
    .def("json_to_midi", &encoder::SteinbergWPCSEncoder::json_to_midi)
    .def("json_track_to_midi", &encoder::SteinbergWPCSEncoder::json_track_to_midi)
    .def("json_to_tokens", &encoder::SteinbergWPCSEncoder::json_to_tokens)
    .def("tokens_to_json", &encoder::SteinbergWPCSEncoder::tokens_to_json)
    .def("tokens_to_midi", &encoder::SteinbergWPCSEncoder::tokens_to_midi)
    .def("pretty", &encoder::SteinbergWPCSEncoder::pretty)
    .def("vocab_size", &encoder::SteinbergWPCSEncoder::vocab_size)
    .def("get_attribute_control_types", &encoder::SteinbergWPCSEncoder::get_attribute_control_types)
    .def_readonly("config", &encoder::SteinbergWPCSEncoder::config)
    .def_readonly("rep", &encoder::SteinbergWPCSEncoder::rep);

  py::class_<encoder::GhostEncoder>(handle, "GhostEncoder")
    .def(py::init<>())
    .def("encode", &encoder::GhostEncoder::encode)
    .def("decode", &encoder::GhostEncoder::decode)
    .def("midi_to_json", &encoder::GhostEncoder::midi_to_json)
    .def("midi_to_tokens", &encoder::GhostEncoder::midi_to_tokens)
    .def("json_to_midi", &encoder::GhostEncoder::json_to_midi)
    .def("json_track_to_midi", &encoder::GhostEncoder::json_track_to_midi)
    .def("json_to_tokens", &encoder::GhostEncoder::json_to_tokens)
    .def("tokens_to_json", &encoder::GhostEncoder::tokens_to_json)
    .def("tokens_to_midi", &encoder::GhostEncoder::tokens_to_midi)
    .def("pretty", &encoder::GhostEncoder::pretty)
    .def("vocab_size", &encoder::GhostEncoder::vocab_size)
    .def("get_attribute_control_types", &encoder::GhostEncoder::get_attribute_control_types)
    .def_readonly("config", &encoder::GhostEncoder::config)
    .def_readonly("rep", &encoder::GhostEncoder::rep);

}
