import sys
import os
import json
import argparse
import time

# Ensure build directory is in path for midigpt
parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(parent_dir, "build"))
sys.path.append(os.path.join(parent_dir, "build_symusic"))
sys.path.append(os.path.join(parent_dir, "src/python"))

try:
    import midigpt
except ImportError:
    print("Error: could not import midigpt. Make sure it's built and available in the build/ directory.")
    sys.exit(1)

# ANSI Color Codes
class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    
    # Custom for simulation
    CONTEXT = '\033[92m'   # Green (Ground Truth)
    CURRENT = '\033[93m'   # Yellow (Active/Masked)
    TARGET = '\033[91m'    # Red (Generation Target)
    GHOST = '\033[96m'     # Cyan (Masked Future)
    EMPTY = '\033[90m'     # Grey

def render_sim_grid(human_track_names, human_bars, agent_bars, playhead, target_bar, selected_sel, mask_lookahead_gap):
    """
    Renders the simulation status grid.
    - human_track_names: List of strings.
    - human_bars: List of lists (Track x Bar).
    - agent_bars: List of bars for the AI agent.
    - playhead: Current bar index being performed.
    - target_bar: The bar index currently being generated by the AI (optional).
    - selected_sel: The boolean mask of selected bars.
    """
    num_bars = len(human_bars[0])
    
    # Header
    gen_indices = [i for i, val in enumerate(selected_sel) if val]
    target_str = f"{min(gen_indices)+1}-{max(gen_indices)+1}" if gen_indices else 'None'
    print(f"\n{Colors.BOLD}LIVE SIMULATION GRID (Playhead: {playhead+1}, Target: {target_str}){Colors.ENDC}")
    print(f"{Colors.CONTEXT}■{Colors.ENDC} = Ground Truth (Notes)  {Colors.CONTEXT}.{Colors.ENDC} = Ground Truth (Silent)  {Colors.CURRENT}M{Colors.ENDC} = Current (Masked)")
    print(f"{Colors.TARGET}G{Colors.ENDC} = Target Generation     {Colors.GHOST}X{Colors.ENDC} = Future Mask")
    print("\n" + " " * 12 + "".join([f"{i:3}" for i in range(num_bars)]))
    print(" " * 11 + " +" + "---" * num_bars)
    
    # Render Human Tracks
    for i, track in enumerate(human_bars):
        name = human_track_names[i]
        line = f"{name:9} | "
        for b in range(num_bars):
            if b < playhead:
                line += f"{Colors.CONTEXT} ■ {Colors.ENDC}"
            elif b == playhead:
                line += f"{Colors.CURRENT} M {Colors.ENDC}"
            else:
                line += f"{Colors.GHOST} X {Colors.ENDC}"
        print(line)
        
    # Render Agent Track
    line = f"Agent     | "
    for b in range(num_bars):
        if selected_sel[b]:
            line += f"{Colors.TARGET} G {Colors.ENDC}"
        elif b < playhead:
            # Agent's past performance (Check for events)
            events = agent_bars[b].get('events', [])
            char = " ■ " if len(events) > 0 else " . "
            line += f"{Colors.CONTEXT}{char}{Colors.ENDC}"
        elif b == playhead:
            if mask_lookahead_gap:
                line += f"{Colors.CURRENT} M {Colors.ENDC}"
            else:
                events = agent_bars[b].get('events', [])
                char = " ■ " if len(events) > 0 else " . "
                line += f"{Colors.CONTEXT}{char}{Colors.ENDC}"
        elif target_bar is not None and b > playhead and b < target_bar:
            if mask_lookahead_gap:
                line += f"{Colors.GHOST} X {Colors.ENDC}"
            else:
                line += f"{Colors.EMPTY} . {Colors.ENDC}"
        else:
            line += f"{Colors.EMPTY} . {Colors.ENDC}"
    print(line)
    print(" " * 11 + " +" + "---" * num_bars)

def main():
    parser = argparse.ArgumentParser(description="Simulate Real-Time MIDI-GPT Agent.")
    parser.add_argument("--midi", type=str, required=True, help="Input MIDI file for human tracks")
    # ckpt not required if just doing dry run grid, but required for sample_multi_step
    parser.add_argument("--ckpt", type=str, help="Path to model checkpoint (.pt)")
    parser.add_argument("--buffer", type=int, default=8, help="Initial bars of silence for human context")
    parser.add_argument("--lookahead", type=int, default=2, help="Bar distance between playhead and generation target (k)")
    parser.add_argument("--num_anticipated_bars", type=int, default=1, help="Number of bars currently being generated in this window (j)")
    parser.add_argument("--agent_instrument", type=int, default=32, help="MIDI program number for the agent (0-127, default: 32)")
    parser.add_argument("--model_dim", type=int, default=8, help="Total sliding window size in bars")
    parser.add_argument("--mask_gap", action="store_true", help="Mask the bars between playhead and target")
    parser.add_argument("--adapt_buffer", action="store_true", help="Start generating early to play immediately after buffer")
    parser.add_argument("--max_attempts", type=int, default=5, help="Max retry attempts for inference")
    parser.add_argument("--delay", type=float, default=0.5, help="Delay between steps for visualization")
    parser.add_argument("--dry_run", action="store_true", help="Just simulate the grid without calling inference")
    parser.add_argument("--output", type=str, help="Path to save the resulting MIDI file")

    args = parser.parse_args()

    # 1. Validation Constraints
    if args.buffer < 2:
        print(f"{Colors.FAIL}Error: buffer ({args.buffer}) must be >= 2. "
              f"The constraint k <= B/2 with k >= 1 requires B >= 2.{Colors.ENDC}")
        sys.exit(1)
    if args.buffer < 4:
        print(f"{Colors.WARNING}Warning: buffer ({args.buffer}) < 4. "
              f"Very little human context at first generation step.{Colors.ENDC}")

    if args.lookahead > args.buffer // 2:
        print(f"{Colors.FAIL}Error: lookahead ({args.lookahead}) must be <= buffer/2 ({args.buffer//2}) for sufficient context.{Colors.ENDC}")
        sys.exit(1)

    if args.lookahead + args.num_anticipated_bars >= args.model_dim:
        print(f"{Colors.FAIL}Error: lookahead + num_anticipated_bars ({args.lookahead + args.num_anticipated_bars}) must be < model_dim ({args.model_dim}).{Colors.ENDC}")
        sys.exit(1)

    # 2. Load Source MIDI
    # Note: TrainConfig is the class used for MIDI parsing configuration (res, bars, etc.)
    # even during inference simulation.
    parse_cfg = midigpt.TrainConfig()
    parse_cfg.resolution = 12
    parse_cfg.num_bars = 1  # Ensures even short MIDIs are parsed
    parse_cfg.min_tracks = 1
    
    print(f"Loading MIDI: {args.midi}...")
    json_bytes = midigpt.midi_to_json_bytes(args.midi, parse_cfg, "{}")
    if not json_bytes:
        print(f"{Colors.FAIL}Error: Failed to parse MIDI file.{Colors.ENDC}")
        sys.exit(1)
        
    piece_str = midigpt.json_bytes_to_string(json_bytes)
    piece = json.loads(piece_str)
    
    # GM Instrument names for StatusTrack (truncated for common ones, index = program number)
    GM_INSTRUMENTS = [
        "acoustic_grand_piano", "bright_acoustic_piano", "electric_grand_piano", "honky_tonk_piano",
        "electric_piano_1", "electric_piano_2", "harpsichord", "clavi", "celesta", "glockenspiel",
        "music_box", "vibraphone", "marimba", "xylophone", "tubular_bells", "dulcimer",
        "drawbar_organ", "percussive_organ", "rock_organ", "church_organ", "reed_organ",
        "accordion", "harmonica", "tango_accordion", "acoustic_guitar_nylon", "acoustic_guitar_steel",
        "electric_guitar_jazz", "electric_guitar_clean", "electric_guitar_muted", "overdriven_guitar",
        "distortion_guitar", "guitar_harmonics", "acoustic_bass", "electric_bass_finger",
        "electric_bass_pick", "fretless_bass", "slap_bass_1", "slap_bass_2", "synth_bass_1", "synth_bass_2",
        "violin", "viola", "cello", "contrabass", "tremolo_strings", "pizzicato_strings",
        "orchestral_harp", "timpani", "string_ensemble_1", "string_ensemble_2", "synth_strings_1", "synth_strings_2",
        "choir_aahs", "voice_oohs", "synth_voice", "orchestra_hit", "trumpet", "trombone", "tuba",
        "muted_trumpet", "french_horn", "brass_section", "synth_brass_1", "synth_brass_2",
        "soprano_sax", "alto_sax", "tenor_sax", "baritone_sax", "oboe", "english_horn", "bassoon", "clarinet",
        "piccolo", "flute", "recorder", "pan_flute", "blown_bottle", "shakuhachi", "whistle", "ocarina",
        "lead_1_square", "lead_2_sawtooth", "lead_3_calliope", "lead_4_chiff", "lead_5_charang", "lead_6_voice",
        "lead_7_fifths", "lead_8_bass__lead", "pad_1_new_age", "pad_2_warm", "pad_3_polysynth", "pad_4_choir",
        "pad_5_bowed", "pad_6_metallic", "pad_7_halo", "pad_8_sweep", "fx_1_rain", "fx_2_soundtrack",
        "fx_3_crystal", "fx_4_atmosphere", "fx_5_brightness", "fx_6_goblins", "fx_7_echoes", "fx_8_sci_fi",
        "sitar", "banjo", "shamisen", "koto", "kalimba", "bag_pipe", "fiddle", "shanai",
        "tinkle_bell", "agogo", "steel_drums", "woodblock", "taiko_drum", "melodic_tom", "synth_drum", "reverse_cymbal",
        "guitar_fret_noise", "breath_noise", "seashore", "bird_tweet", "telephone_ring", "helicopter", "applause", "gunshot"
    ]
    
    # 2.1 Sanitize Track Types for GhostEncoder
    # The ghost encoder only supports STANDARD_TRACK (10) and STANDARD_DRUM_TRACK (11)
    # Auxiliary types (8, 9) must be mapped to these.
    for track in piece.get('tracks', []):
        tt = track.get('track_type', 10)
        if tt == 8: # AUX_DRUM_TRACK
            track['track_type'] = 11 # STANDARD_DRUM_TRACK
        elif tt == 9: # AUX_INST_TRACK
            track['track_type'] = 10 # STANDARD_TRACK
        elif tt not in [10, 11]:
            # Default to standard track if unknown
            track['track_type'] = 10
    
    # 3. Setup Simulation State
    # Human tracks are tracks 0 and 1 (if available)
    num_human = min(2, len(piece['tracks']))
    human_tracks_data = piece['tracks'][:num_human]
    
    # MIDI song length
    song_bars = len(human_tracks_data[0]['bars'])
    
    # C++ validator requires status.selected_bars_size >= model_dim
    # So we pad the piece if it's shorter than model_dim
    pad_bars = max(0, args.model_dim - song_bars)
    total_bars = song_bars + pad_bars
    
    if args.buffer >= song_bars:
        print(f"{Colors.WARNING}Warning: Buffer ({args.buffer}) is >= song bars ({song_bars}). The AI will not generate anything because simulation ends before the buffer is met.{Colors.ENDC}")
    
    # Pad Human Tracks
    for track in human_tracks_data:
        track['bars'].extend([{"ts_numerator": 4, "ts_denominator": 4, "events": []} for _ in range(pad_bars)])
        
    human_track_names = [f"Human {i}" for i in range(num_human)]
    
    # Agent's generated material track 
    agent_bars = [{"ts_numerator": 4, "ts_denominator": 4} for _ in range(total_bars)]
    
    # Global Piece (Maintained across steps)
    # Piece events are shared.
    sim_piece = {
        "tracks": human_tracks_data + [{"instrument": args.agent_instrument, "track_type": 10, "bars": agent_bars}],
        "resolution": piece.get('resolution', 12),
        "events": piece.get('events', [])
    }
    
    # 4. Simulation Loop
    print(f"{Colors.OKCYAN}Starting Real-Time Simulation Loop...{Colors.ENDC}")
    print(f"Buffer: {args.buffer}, Lookahead: {args.lookahead}, Anticipated: {args.num_anticipated_bars}, ModelDim: {args.model_dim}")
    if args.dry_run:
        print(f"{Colors.WARNING}Dry Run Mode: Inference calls are disabled.{Colors.ENDC}")

    playhead = 0

    while playhead < total_bars:
        # Determine generation target
        target_bar = None
        should_gen = False
        num_anticipation = args.num_anticipated_bars

        if args.adapt_buffer:
            if playhead + args.lookahead >= args.buffer:
                target_bar = playhead + args.lookahead
        else:
            if playhead >= args.buffer:
                target_bar = playhead + args.lookahead

        if target_bar is not None:
            if target_bar < args.buffer:
                target_bar = None
            elif target_bar < total_bars:
                should_gen = not args.dry_run
                # Clamp to avoid overshooting the piece end
                num_anticipation = min(args.num_anticipated_bars, total_bars - target_bar)
            else:
                target_bar = None

        # Build per-track status bars with future flags.
        # future flags live in StatusBar (status side), not in the piece.
        # The C++ preprocessing step copies StatusBar.future → Bar.future before encoding.

        # Human tracks: future=True for bars at or after playhead (not yet performed)
        human_status_bars = [
            [{"future": b >= playhead} for b in range(total_bars)]
            for _ in range(num_human)
        ]

        # Agent track future flags
        agent_status_bars = []
        sel = [False] * total_bars
        if target_bar is not None:
            # Select exactly [target_bar, target_bar + num_anticipation) — BUG 1 FIX
            for b_idx in range(target_bar, min(target_bar + num_anticipation, total_bars)):
                sel[b_idx] = True

            for b in range(total_bars):
                if b >= target_bar + num_anticipation:
                    # Beyond generation window: future (not generated yet)
                    agent_status_bars.append({"future": True})
                elif args.mask_gap and playhead <= b < target_bar:
                    # Gap bars [playhead, target_bar): hide prior lookahead output — BUG 3 FIX
                    agent_status_bars.append({"future": True})
                else:
                    # Context bars [0, playhead) + gap (unmasked) + target bars: visible
                    agent_status_bars.append({"future": False})
        else:
            agent_status_bars = [{"future": False}] * total_bars

        # Assemble status dict
        status = {"tracks": []}
        for i in range(num_human):
            h_track = sim_piece['tracks'][i]
            status['tracks'].append({
                "track_id": i,
                "track_type": h_track.get('track_type', 10),
                "selected_bars": [False] * total_bars,
                "suffix_autoregressive": False,
                "temperature": 1.0,
                "polyphony_hard_limit": 10,
                "bars": human_status_bars[i],
            })

        a_track = sim_piece['tracks'][num_human]
        agent_inst_name = "acoustic_bass"
        if 0 <= args.agent_instrument < len(GM_INSTRUMENTS):
            agent_inst_name = GM_INSTRUMENTS[args.agent_instrument]

        status['tracks'].append({
            "track_id": num_human,
            "track_type": a_track.get('track_type', 10),
            "selected_bars": sel,
            "suffix_autoregressive": True,
            "temperature": 1.0,
            "polyphony_hard_limit": 10,
            "instrument": agent_inst_name,
            "bars": agent_status_bars,
        })

        # Render visualization
        h_bars = [t['bars'] for t in sim_piece['tracks'][:num_human]]
        render_sim_grid(human_track_names, h_bars, agent_bars, playhead, target_bar, sel, args.mask_gap)

        if target_bar is not None:
            print(f" {Colors.BOLD}Inference Phase:{Colors.ENDC} Generation target starts at Bar {target_bar + 1}")
            print(f"{Colors.OKCYAN}MASKING SUMMARY (STATUS):{Colors.ENDC}")
            for i, track in enumerate(status['tracks']):
                name = human_track_names[i] if i < num_human else "Agent"
                masked = [b for b, sb in enumerate(track.get('bars', [])) if sb.get('future')]
                print(f"  {name:9} | future=True for bars: {masked}")

            print(f"{Colors.OKCYAN}SELECTED BARS FOR GENERATION (STATUS):{Colors.ENDC}")
            for i, track in enumerate(status['tracks']):
                name = human_track_names[i] if i < num_human else "Agent"
                sel_bars = [b for b, b_sel in enumerate(track['selected_bars']) if b_sel]
                print(f"  {name:9} | selected=True for bars: {sel_bars}")

            if should_gen:
                params = {
                    "model_dim": args.model_dim,
                    "temperature": 1.0,
                    "batch_size": 1,
                    "ckpt": args.ckpt,
                    "bars_per_step": num_anticipation,
                    "tracks_per_step": 1,
                    "percentage": 100,
                    "polyphony_hard_limit": 10
                }

                try:
                    res_str, attempts = midigpt.sample_multi_step(
                        json.dumps(sim_piece),
                        json.dumps(status),
                        json.dumps(params),
                        args.max_attempts,
                        None
                    )

                    res_piece = json.loads(res_str)
                    res_events = res_piece.get('events', [])
                    res_agent_track = res_piece['tracks'][num_human]

                    # Write back all j generated bars — BUG 4 FIX
                    total_new_events = 0
                    for b_offset in range(num_anticipation):
                        b_global = target_bar + b_offset
                        if b_global >= total_bars:
                            break
                        res_bar = res_agent_track['bars'][b_global]
                        # Append event objects to the global pool, track indices
                        new_event_indices = []
                        for ev_idx in res_bar.get('events', []):
                            new_global_idx = len(sim_piece['events'])
                            sim_piece['events'].append(res_events[ev_idx])
                            new_event_indices.append(new_global_idx)
                        agent_bars[b_global]['events'] = new_event_indices
                        total_new_events += len(new_event_indices)

                    print(f" {Colors.OKGREEN}Result:{Colors.ENDC} Generated {total_new_events} events across {num_anticipation} bar(s).")

                except Exception as e:
                    print(f" {Colors.FAIL}Inference Call Failed:{Colors.ENDC} {e}")
            else:
                print(f" {Colors.GHOST}[Dry Run: Inference call skipped]{Colors.ENDC}")

        time.sleep(args.delay)

        # Advance playhead: by j after each generation step, by 1 during buffer — BUG 5 FIX
        if should_gen:
            playhead += num_anticipation
        else:
            playhead += 1

    print(f"\n{Colors.OKGREEN}Simulation Concluded.{Colors.ENDC}")

    # 10. Save Output MIDI if requested
    if args.output and not args.dry_run:
        print(f"Saving resulting MIDI to {args.output}...")
        
        # Ensure directory exists
        out_dir = os.path.dirname(args.output)
        if out_dir and not os.path.exists(out_dir):
            os.makedirs(out_dir)
            
        # Convert dict to JSON string then call C++ write_midi
        final_json_str = json.dumps(sim_piece)
        midigpt.write_midi(final_json_str, args.output)
        print(f"{Colors.OKCYAN}File saved successfully.{Colors.ENDC}")

if __name__ == "__main__":
    main()
